spring:
  application:
    name: auction
  datasource:
    url: ${SUPABASE_DB_URL:jdbc:h2:mem:testdb}
    username: ${SUPABASE_DB_USERNAME:sa}
    password: ${SUPABASE_DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

server:
  error:
    include-stacktrace: never
