CREATE TABLE IF NOT EXISTS auctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    start_price NUMERIC(19,2) NOT NULL,
    min_increment NUMERIC(19,2) NOT NULL,
    current_highest_bid NUMERIC(19,2),
    duration_minutes INT NOT NULL,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
