CREATE TABLE IF NOT EXISTS bids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id BIGINT NOT NULL,
    amount NUMERIC(19,2) NOT NULL,
    bidder_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_bid_auction FOREIGN KEY (auction_id) REFERENCES auctions (id)
);
